member/urls.py
from django.conf.urls import url

from .views import IndexView, AddView, ItemView, EditView

app_name = 'member'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^add/$', AddView.as_view(), name='add'),
    url(r'^(?P<pk>\d+)/$', ItemView.as_view(), name='item'),
    url(r'^(?P<pk>\d+)/edit/$', EditView.as_view(), name='edit'),
]

organ/urls.py
from django.conf import settings
from django.conf.urls import url, include

from web.views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='index'),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^avatar/', include('avatar.urls', namespace='avatar')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^member/', include('member.urls', namespace='member')),
]

if settings.ADMIN_ENABLED:
    from django.contrib import admin

    urlpatterns += [
        url(r'^admin/', admin.site.urls),
    ]

if settings.DEBUG:
    from django.views.static import serve

    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, name='static', kwargs={'document_root': settings.STATIC_ROOT}),
    ]

member/models.py
from django.contrib.auth import get_user_model
from django.db import models
from djext.blame.models import BaseBlameModel


AccountModel = get_user_model()


class Member(BaseBlameModel):
    """
    A model of member

    member_id (int): An internal member id
    user: A link to a login user account (optional)
    first_name (str): The member's first name
    last_name (str): The member's last name
    id_type (str): Type of the ID document (usually National or passport)
    id_number (int): ID number of the member
    locale (str): Preferred locale of the member (
    """
    member_id = models.IntegerField(db_index=True)
    user = models.OneToOneField(AccountModel, blank=True, null=True, related_name='member')
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    id_type = models.CharField(max_length=32)
    id_number = models.CharField(max_length=32)

    locale = models.CharField(max_length=5, null=True, blank=True)

    def get_absolute_url(self):
        return '/member/{id}/'.format(id=self.id)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '{first_name} {last_name}'.format(first_name=self.first_name, last_name=self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def __str__(self):
        return self.get_full_name()


class MembershipType(models.Model):
    name = models.CharField(max_length=32)
    period = models.CharField(max_length=16, null=True, blank=True)

    def __str__(self):
        return self.name


class Membership(BaseBlameModel):
    member = models.ForeignKey(Member, related_name='memberships')
    membership_type = models.ForeignKey(MembershipType)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        with self as membership:
            return '{membership.member} ({membership.membership_type})'.format(membership=membership)


class MemberContactDetail(BaseBlameModel):
    primary = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class MemberEmail(MemberContactDetail):
    member = models.ForeignKey(Member, related_name='emails')
    email = models.EmailField(max_length=255)

    def __str__(self):
        return self.email


class MemberPhone(MemberContactDetail):
    member = models.ForeignKey(Member, related_name='phones')
    phone = models.CharField(max_length=20)
    text_only = models.BooleanField(default=False)

    def __str__(self):
        return self.phone


class MemberAddress(MemberContactDetail):
    member = models.ForeignKey(Member, related_name='addresses')
    country = models.CharField(max_length=32)
    state = models.CharField(max_length=32)
    zip_code = models.CharField(max_length=16)
    city = models.CharField(max_length=64)
    pob = models.CharField(max_length=32)
    street = models.CharField(max_length=64)
    house = models.CharField(max_length=32)

    def __str__(self):
        return self.state

member/forms.py
from djext.blame.forms import BlameForm

from .models import Member, Membership, MemberEmail, MemberPhone, MemberAddress


class MemberForm(BlameForm):
    class Meta:
        model = Member
        fields = ['member_id', 'first_name', 'last_name', 'id_type', 'id_number', 'locale']


class MemberFromUserForm(BlameForm):
    def save(self, commit=True):
        self.instance.user = self.user
        self.instance.first_name = self.user.first_name
        self.instance.last_name = self.user.last_name
        return super().save(commit)

    class Meta:
        model = Member
        fields = ['member_id', 'id_type', 'id_number', 'locale']


class MemberSubFormMixin(object):
    def __init__(self, *args, **kwargs):
        self.member = kwargs.pop('member')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.member = self.member
        return super().save(commit)


class MembershipForm(MemberSubFormMixin, BlameForm):
    class Meta:
        model = Membership
        fields = ['membership_type', 'start_date', 'end_date']


class MemberEmailForm(MemberSubFormMixin, BlameForm):
    class Meta:
        model = MemberEmail
        fields = ['email']


class MemberPhoneForm(MemberSubFormMixin, BlameForm):
    class Meta:
        model = MemberPhone
        fields = ['phone', 'text_only']


class MemberAddressForm(MemberSubFormMixin, BlameForm):
    class Meta:
        model = MemberAddress
        fields = ['street', 'house', 'pob', 'city', 'zip_code', 'state']

member/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from djext.blame.views import BlameFormView

from member.models import MembershipType
from .forms import MemberForm, MemberPhoneForm, MemberEmailForm
from .models import Member


class IndexView(LoginRequiredMixin, ListView):
    model = Member


class AddView(LoginRequiredMixin, BlameFormView, CreateView):
    model = Member
    form_class = MemberForm
    template_name_suffix = '_create_form'

    def get_success_url(self):
        if self.object:
            return reverse('member:item', kwargs={'pk': self.object.id})
        else:
            return reverse('member:index')


class ItemView(LoginRequiredMixin, DetailView):
    model = Member

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['phone_form'] = MemberPhoneForm(member=self.object, user=self.request.user)
        context['email_form'] = MemberEmailForm(member=self.object, user=self.request.user)

        membership_types = MembershipType.objects.all()
        context['membership_types'] = membership_types

        return context


class EditView(LoginRequiredMixin, BlameFormView, UpdateView):
    model = Member
    form_class = MemberForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse('member:item', kwargs={'pk': self.object.id})

member/templates/member/member_create_form.html
{% extends 'site_base.html' %}

{% block header-title %}Add member{% endblock %}

{% block content %}
    <div class="box">
        <form class="form-horizontal" action="{% url 'member:add' %}" method="post">
            <div class="box-body">
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="box-footer">
                {% csrf_token %}
                <a class="btn btn-link" href="{% url 'member:index' %}">Back to list</a>
                <button class="btn btn-success">Add</button>
            </div>
        </form>
    </div>
{% endblock %}

member/templates/member/member_detail.html
{% extends 'site_base.html' %}

{% block header-title %}Member{% endblock %}

{% block header-subtitle %}{{ member.get_full_name }}{% endblock %}

{% block content %}
<div class="box">
    <div class="box-body">
        <dl>
            <dt>Name</dt>
            <dd>{{ member.get_full_name }}</dd>
        </dl>
    </div>
</div>

{% include 'member/partials/membership_box.html' with membership_list=member.memberships.all %}

<div class="row">
    <div class="col-md-6">
        {% include 'member/partials/phone_box.html' with phone_list=member.phones.all active_only=1 form=phone_form %}
    </div>
    <div class="col-md-6">
        {% include 'member/partials/email_box.html' with email_list=member.emails.all active_only=1 form=email_form %}
    </div>
</div>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Addresses</h3>
    </div>
    <div class="box-body">
        {% include 'member/partials/address_table.html' with address_list=member.addresses.all active_only=1 %}
    </div>
    <div class="box-footer"></div>
</div>
{% endblock %}

member/templates/member/member_list.html
{% extends 'site_base.html' %}

{% block content %}
    <div class="box box-info">
        <div class="box-body">
            <a href="{% url 'member:add' %}" class="btn btn-success">
                <i class="fa fa-plus-circle"></i>
                Add member
            </a>
            <table class="table table-responsive table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    {% for member in member_list %}
                    <tr>
                        <td></td>
                        <td>
                            <a href="{% url 'member:item' member.id %}">{{ member }}</a>
                        </td>
                        <td>{{ member.emails.first }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">No members</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

member/templates/member/member_update_form.html
{% extends 'site_base.html' %}

{% block content %}
{{ form }}
{% endblock %}